resource_path: ["../"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true
filters:
  - include-code-files

project:
  type: website
  output-dir: "../_site"
  render:
    - index.md
    - general_information.md
    - acknowledgements.md
    - phd_timeline.md
    - phd_thesis.md
    - masters_info.md
    - fusion.md
    - courses.md
    - conferences.md
    - journals.md
    - office365.md
    - expenses_and_travel.md
    - learning_resources.md
    - events.md
    - living_in_denmark.md
    - departing.md

website:
  title: "QMCM Handbook"
  navbar:
    tools:
      - icon: github
        url:  https://github.com/dtu-qmcm/qmcm_handbook
  sidebar:
    style: "docked"
    serach: true
    contents:
      - index.md
      - general_information.md
      - acknowledgements.md
      - phd_timeline.md
      - phd_thesis.md
      - masters_info.md
      - fusion.md
      - courses.md
      - conferences.md
      - journals.md
      - office365.md
      - expenses_and_travel.md
      - learning_resources.md
      - events.md
      - living_in_denmark.md
      - departing.md

format:
  html:
    theme: cosmo
    embed-resources: true
    include-in-header: mathjax.html
